import { cn } from "@/lib/utils"
import { Providers } from "@/modules/providers"
import "@/styles/globals.css"
import { Inter as FontSans } from "next/font/google"

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning className={fontSans.variable}>
            <body
                className={cn(
                    "flex min-h-screen flex-col font-sans antialiased"
                )}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
